[project]
name = "vesta-diary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "psycopg2-binary>=2.9.10",
    "uvicorn>=0.34.2",
]
